DESIGN_NAME: ahb_counter
FP_PDN_MULTILAYER: false
CLOCK_PORT: HCLK
CLOCK_PERIOD: 23
VERILOG_FILES:
    - dir::../../verilog/rtl/ahb_counter.v
PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc
DESIGN_REPAIR_MAX_WIRE_LENGTH: 700
RUN_POST_GRT_DESIGN_REPAIR: true
FP_SIZING: absolute
DIE_AREA: [0, 0, 400, 200]
CORE_AREA: [10, 10, 390, 190]
PL_TARGET_DENSITY_PCT: 50
RUN_POST_GRT_RESIZER_TIMING: true
TIME_DERATING_CONSTRAINT: 8.0
VDD_NETS: 
    - vccd1
GND_NETS: 
    - vssd1
FP_PIN_ORDER_CFG: dir::pin_order.cfg
