# generated by get_frigate_upw_sdc.py
# Date: 2025/02/03

### Note:
# - IO ports are assumed to be asynchronous. If they're synchronous to the clock, update the variable IO_SYNC to 1.
#   As well, update in_ext_delay and out_ext_delay with the required I/O external delays.

#------------------------------------------#
# Pre-defined Constraints
#------------------------------------------#

# Clock network
if {[info exists ::env(CLOCK_PORT)] && $::env(CLOCK_PORT) != ""} {
	set clk_input $::env(CLOCK_PORT)
	create_clock [get_ports $clk_input] -name clk -period $::env(CLOCK_PERIOD)
	puts "\[INFO\]: Creating clock {clk} for port $clk_input with period: $::env(CLOCK_PERIOD)"
} else {
	set clk_input __VIRTUAL_CLK__
	create_clock -name clk -period $::env(CLOCK_PERIOD)
	puts "\[INFO\]: Creating virtual clock with period: $::env(CLOCK_PERIOD)"
}
if { ![info exists ::env(SYNTH_CLK_DRIVING_CELL)] } {
	set ::env(SYNTH_CLK_DRIVING_CELL) $::env(SYNTH_DRIVING_CELL)
}
if { ![info exists ::env(SYNTH_CLK_DRIVING_CELL_PIN)] } {
	set ::env(SYNTH_CLK_DRIVING_CELL_PIN) $::env(SYNTH_DRIVING_CELL_PIN)
}

# Clock non-idealities
set_propagated_clock [all_clocks]
set_clock_uncertainty $::env(CLOCK_UNCERTAINTY_CONSTRAINT) [get_clocks {clk}]
puts "\[INFO\]: Setting clock uncertainity to: $::env(CLOCK_UNCERTAINTY_CONSTRAINT)"
set_clock_transition $::env(CLOCK_TRANSITION_CONSTRAINT) [get_clocks {clk}]
puts "\[INFO\]: Setting clock transition to: $::env(CLOCK_TRANSITION_CONSTRAINT)"

# Maximum transition time for the design nets
set_max_transition $::env(MAX_TRANSITION_CONSTRAINT) [current_design]
puts "\[INFO\]: Setting maximum transition to: $::env(MAX_TRANSITION_CONSTRAINT)"

# Maximum fanout
set_max_fanout $::env(MAX_FANOUT_CONSTRAINT) [current_design]
puts "\[INFO\]: Setting maximum fanout to: $::env(MAX_FANOUT_CONSTRAINT)"

# Timing paths delays derate
set_timing_derate -early [expr {1-$::env(TIME_DERATING_CONSTRAINT)/100}]
set_timing_derate -late [expr {1+$::env(TIME_DERATING_CONSTRAINT)/100}]
puts "\[INFO\]: Setting timing derate to: $::env(TIME_DERATING_CONSTRAINT) %"

#------------------------------------------#
# Retrieved Constraints
#------------------------------------------#

# Clock source latency
set clk_max_latency 4.85
set clk_min_latency 2.22
set_clock_latency -source -max $clk_max_latency [get_clocks {clk}]
set_clock_latency -source -min $clk_min_latency [get_clocks {clk}]
puts "\[INFO\]: Setting clock latency range: $clk_min_latency : $clk_max_latency"

# Clock input Transition
set clk_tran 1.37
set_input_transition $clk_tran [get_ports $clk_input]
puts "\[INFO\]: Setting clock transition: $clk_tran"

# Input delays
set_input_delay -max 10.38  -clock [get_clocks {clk}] [get_ports {HTRANS[*]}]
set_input_delay -max 10.97  -clock [get_clocks {clk}] [get_ports {HWRITE}]
set_input_delay -max 11.76  -clock [get_clocks {clk}] [get_ports {HSIZE[*]}]
set_input_delay -max 12.12  -clock [get_clocks {clk}] [get_ports {HADDR[*]}]
set_input_delay -max 4.01   -clock [get_clocks {clk}] [get_ports {HRESETn}]
set_input_delay -max 4.58   -clock [get_clocks {clk}] [get_ports {HREADY}]
set_input_delay -max 6.11   -clock [get_clocks {clk}] [get_ports {HWDATA[*]}]
set_input_delay -min 0.63   -clock [get_clocks {clk}] [get_ports {HWRITE}]
set_input_delay -min 0.7    -clock [get_clocks {clk}] [get_ports {HADDR[*]}]
set_input_delay -min 0.83   -clock [get_clocks {clk}] [get_ports {HSIZE[*]}]
set_input_delay -min 0.87   -clock [get_clocks {clk}] [get_ports {HTRANS[*]}]
set_input_delay -min 1.05   -clock [get_clocks {clk}] [get_ports {HWDATA[*]}]
set_input_delay -min 1.18   -clock [get_clocks {clk}] [get_ports {HREADY}]
set_input_delay -min 2.33   -clock [get_clocks {clk}] [get_ports {HRESETn}]
if { $::env(IO_SYNC) } {
	set in_ext_delay 4
	puts "\[INFO\]: Setting input ports external delay to: $in_ext_delay"
	set_input_delay -max [expr $in_ext_delay + 1.24  ] -clock [get_clocks {clk}] [get_ports {gpio1_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 1.24  ] -clock [get_clocks {clk}] [get_ports {gpio2_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 1.24  ] -clock [get_clocks {clk}] [get_ports {gpio5_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 1.24  ] -clock [get_clocks {clk}] [get_ports {gpio6_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 1.65  ] -clock [get_clocks {clk}] [get_ports {gpio0_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 1.69  ] -clock [get_clocks {clk}] [get_ports {sio_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 2.55  ] -clock [get_clocks {clk}] [get_ports {gpio7_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 2.56  ] -clock [get_clocks {clk}] [get_ports {gpio4_in[*]}]
	set_input_delay -max [expr $in_ext_delay + 2.58  ] -clock [get_clocks {clk}] [get_ports {gpio3_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.08  ] -clock [get_clocks {clk}] [get_ports {gpio1_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.09  ] -clock [get_clocks {clk}] [get_ports {gpio6_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.13  ] -clock [get_clocks {clk}] [get_ports {gpio0_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.13  ] -clock [get_clocks {clk}] [get_ports {gpio2_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.13  ] -clock [get_clocks {clk}] [get_ports {gpio5_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.14  ] -clock [get_clocks {clk}] [get_ports {gpio3_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.14  ] -clock [get_clocks {clk}] [get_ports {gpio4_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.32  ] -clock [get_clocks {clk}] [get_ports {gpio7_in[*]}]
	set_input_delay -min [expr $in_ext_delay + 0.46  ] -clock [get_clocks {clk}] [get_ports {sio_in[*]}]
}

# Input Transition
set_input_transition -max 0.08 [get_ports {gpio1_in[*]}]
set_input_transition -max 0.08 [get_ports {gpio6_in[*]}]
set_input_transition -max 0.09 [get_ports {gpio7_in[*]}]
set_input_transition -max 0.1  [get_ports {gpio3_in[*]}]
set_input_transition -max 0.1  [get_ports {gpio4_in[*]}]
set_input_transition -max 0.11 [get_ports {gpio0_in[*]}]
set_input_transition -max 0.12 [get_ports {HSIZE[*]}]
set_input_transition -max 0.13 [get_ports {HREADY}]
set_input_transition -max 0.14 [get_ports {gpio2_in[*]}]
set_input_transition -max 0.14 [get_ports {gpio5_in[*]}]
set_input_transition -max 0.17 [get_ports {sio_in[*]}]
set_input_transition -max 0.26 [get_ports {HWRITE}]
set_input_transition -max 0.32 [get_ports {HTRANS[*]}]
set_input_transition -max 0.49 [get_ports {HWDATA[*]}]
set_input_transition -max 0.62 [get_ports {HRESETn}]
set_input_transition -max 0.67 [get_ports {HADDR[*]}]
set_input_transition -min 0.03 [get_ports {gpio7_in[*]}]
set_input_transition -min 0.04 [get_ports {HADDR[*]}]
set_input_transition -min 0.04 [get_ports {HWDATA[*]}]
set_input_transition -min 0.05 [get_ports {gpio1_in[*]}]
set_input_transition -min 0.05 [get_ports {gpio6_in[*]}]
set_input_transition -min 0.06 [get_ports {gpio3_in[*]}]
set_input_transition -min 0.09 [get_ports {gpio4_in[*]}]
set_input_transition -min 0.11 [get_ports {gpio0_in[*]}]
set_input_transition -min 0.12 [get_ports {HSIZE[*]}]
set_input_transition -min 0.14 [get_ports {gpio2_in[*]}]
set_input_transition -min 0.14 [get_ports {gpio5_in[*]}]
set_input_transition -min 0.17 [get_ports {sio_in[*]}]
set_input_transition -min 0.26 [get_ports {HWRITE}]
set_input_transition -min 0.27 [get_ports {HRESETn}]
set_input_transition -min 0.28 [get_ports {HREADY}]
set_input_transition -min 0.32 [get_ports {HTRANS[*]}]

# Output delays
set_output_delay -max 6.19   -clock [get_clocks {clk}] [get_ports {user_irq[*]}]
set_output_delay -max 7.54   -clock [get_clocks {clk}] [get_ports {HRDATA[*]}]
set_output_delay -max 9.8    -clock [get_clocks {clk}] [get_ports {HREADYOUT}]
set_output_delay -min 0.01   -clock [get_clocks {clk}] [get_ports {HRDATA[*]}]
set_output_delay -min 0.39   -clock [get_clocks {clk}] [get_ports {user_irq[*]}]
set_output_delay -min 0.83   -clock [get_clocks {clk}] [get_ports {HREADYOUT}]
if { $::env(IO_SYNC) } {
	set out_ext_delay 4
	puts "\[INFO\]: Setting output ports external delay to: $out_ext_delay"
	set_output_delay -max [expr $out_ext_delay + 1.3   ] -clock [get_clocks {clk}] [get_ports {gpio6_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.49  ] -clock [get_clocks {clk}] [get_ports {gpio1_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.64  ] -clock [get_clocks {clk}] [get_ports {gpio6_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.7   ] -clock [get_clocks {clk}] [get_ports {gpio1_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.7   ] -clock [get_clocks {clk}] [get_ports {gpio5_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.77  ] -clock [get_clocks {clk}] [get_ports {gpio0_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.77  ] -clock [get_clocks {clk}] [get_ports {gpio2_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.93  ] -clock [get_clocks {clk}] [get_ports {sio_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.95  ] -clock [get_clocks {clk}] [get_ports {gpio0_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 1.95  ] -clock [get_clocks {clk}] [get_ports {gpio5_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.08  ] -clock [get_clocks {clk}] [get_ports {gpio2_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.1   ] -clock [get_clocks {clk}] [get_ports {sio_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.25  ] -clock [get_clocks {clk}] [get_ports {gpio7_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.49  ] -clock [get_clocks {clk}] [get_ports {gpio7_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.78  ] -clock [get_clocks {clk}] [get_ports {gpio4_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.9   ] -clock [get_clocks {clk}] [get_ports {gpio4_out[*]}]
	set_output_delay -max [expr $out_ext_delay + 2.99  ] -clock [get_clocks {clk}] [get_ports {gpio3_oeb[*]}]
	set_output_delay -max [expr $out_ext_delay + 3.7   ] -clock [get_clocks {clk}] [get_ports {gpio3_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.19 ] -clock [get_clocks {clk}] [get_ports {gpio6_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.21 ] -clock [get_clocks {clk}] [get_ports {gpio0_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.29 ] -clock [get_clocks {clk}] [get_ports {gpio1_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.32 ] -clock [get_clocks {clk}] [get_ports {gpio0_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.48 ] -clock [get_clocks {clk}] [get_ports {gpio1_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.51 ] -clock [get_clocks {clk}] [get_ports {gpio5_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.56 ] -clock [get_clocks {clk}] [get_ports {gpio7_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.69 ] -clock [get_clocks {clk}] [get_ports {gpio2_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.75 ] -clock [get_clocks {clk}] [get_ports {gpio6_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.76 ] -clock [get_clocks {clk}] [get_ports {gpio5_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.88 ] -clock [get_clocks {clk}] [get_ports {gpio7_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -0.97 ] -clock [get_clocks {clk}] [get_ports {gpio2_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -1.21 ] -clock [get_clocks {clk}] [get_ports {gpio3_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -1.29 ] -clock [get_clocks {clk}] [get_ports {gpio4_out[*]}]
	set_output_delay -min [expr $out_ext_delay + -1.5  ] -clock [get_clocks {clk}] [get_ports {gpio4_oeb[*]}]
	set_output_delay -min [expr $out_ext_delay + -2.03 ] -clock [get_clocks {clk}] [get_ports {gpio3_out[*]}]
	set_output_delay -min [expr $out_ext_delay + 0.01  ] -clock [get_clocks {clk}] [get_ports {sio_out[*]}]
	set_output_delay -min [expr $out_ext_delay + 0.05  ] -clock [get_clocks {clk}] [get_ports {sio_oeb[*]}]
}

# Output loads
set avg_load 0.10
set max_load 0.29
set_load $max_load [all_outputs]
