# Design files
VERILOG_FILES:
    - dir::../../verilog/rtl/defines.v
    - dir::../../verilog/rtl/ahb_counter.v
    - dir::../../verilog/rtl/user_project_wrapper.v
PNR_SDC_FILE: dir::base.sdc

# Hardening strategy variables (this is for 2-Full-Wrapper Flattening). Visit https://docs.google.com/document/d/1pf-wbpgjeNEM-1TcvX2OJTkHjqH_C9p-LURCASS0Zo8 for more info
SYNTH_ELABORATE_ONLY: false
RUN_POST_GPL_DESIGN_REPAIR: true
RUN_POST_CTS_RESIZER_TIMING: true
FP_PDN_ENABLE_RAILS: true
RUN_ANTENNA_REPAIR: true
RUN_FILL_INSERTION: true
RUN_TAP_ENDCAP_INSERTION: true
RUN_CTS: true
RUN_IRDROP_REPORT: false

# PDN configurations
FP_PDN_VOFFSET: 15
FP_PDN_HOFFSET: 15
FP_PDN_VWIDTH: 3.1
FP_PDN_HWIDTH: 3.1
FP_PDN_VSPACING: 15.5
FP_PDN_HSPACING: 15.5
FP_PDN_VPITCH: 90
FP_PDN_HPITCH: 90
ERROR_ON_PDN_VIOLATIONS: false

# Magic variables 
MAGIC_DRC_USE_GDS: true

# Project-specific Configurations
ERROR_ON_SYNTH_CHECKS: false
