# Fixed configurations for frigate. You should NOT edit this section
DESIGN_NAME: user_project_wrapper
FP_SIZING: absolute
DIE_AREA: [0, 0, 2720, 2300]
CORE_AREA: [10, 10, 2710, 2290]
FP_DEF_TEMPLATE: dir::fixed_dont_change/user_project_wrapper.def
VDD_NETS: 
    - vccd1
    - vccd2
GND_NETS: 
    - vssd1
    - vssd2
PDN_OBSTRUCTIONS:
    - met4 1664 2293 1758 2300
    - met4 19 0 224 4
    - met4 2496 0 2701 4
ROUTING_OBSTRUCTIONS: 
    - met4 1664 2293 1758 2300
    - met4 19 0 224 4
    - met4 2496 0 2701 4
FP_PDN_CORE_RING: true
FP_PDN_CORE_RING_VWIDTH: 3.1
FP_PDN_CORE_RING_HWIDTH: 3.1
FP_PDN_CORE_RING_VOFFSET: 15
FP_PDN_CORE_RING_HOFFSET: 15
FP_PDN_CORE_RING_VSPACING: 1.7
FP_PDN_CORE_RING_HSPACING: 1.7
CLOCK_PORT: HCLK
SIGNOFF_SDC_FILE: dir::signoff.sdc
MAGIC_DEF_LABELS: false
CLOCK_PERIOD: 25
MAGIC_ZEROIZE_ORIGIN: false

# Add multiple pins for analog power 
FP_TEMPLATE_COPY_POWER_PINS: true
FP_TEMPLATE_MATCH_MODE: permissive