# Design files
VERILOG_FILES:
    - dir::../../verilog/rtl/defines.v
    - dir::../../verilog/rtl/user_project_wrapper.v
PNR_SDC_FILE: dir::base.sdc

# Hardening strategy variables (this is for 1-Macro-First Hardening). Visit https://docs.google.com/document/d/1pf-wbpgjeNEM-1TcvX2OJTkHjqH_C9p-LURCASS0Zo8 for more info
SYNTH_ELABORATE_ONLY: true
RUN_POST_GPL_DESIGN_REPAIR: false
RUN_POST_CTS_RESIZER_TIMING: false
DESIGN_REPAIR_BUFFER_INPUT_PORTS: false
FP_PDN_ENABLE_RAILS: false
RUN_ANTENNA_REPAIR: false
RUN_FILL_INSERTION: false
RUN_TAP_ENDCAP_INSERTION: false
RUN_CTS: false
RUN_IRDROP_REPORT: false
ERROR_ON_SYNTH_CHECKS: false

# Macros configurations
MACROS:
    ahb_counter: 
        gds: dir::../../gds/ahb_counter.gds
        lef: dir::../../lef/ahb_counter.lef
        instances:
            frigate_prj:
                location: [450, 450]
                orientation: "N"
        nl: dir::../../verilog/gl/ahb_counter.v
        spef:
            min_*: dir::../../spef/multicorner/ahb_counter.min.spef
            nom_*: dir::../../spef/multicorner/ahb_counter.nom.spef
            max_*: dir::../../spef/multicorner/ahb_counter.max.spef
        lib:
            "*": dir::../../lib/ahb_counter.lib
PDN_MACRO_CONNECTIONS: 
    - frigate_prj vccd1 vssd1 vccd1 vssd1

# PDN configurations
FP_PDN_VOFFSET: 15
FP_PDN_HOFFSET: 15
FP_PDN_VWIDTH: 3.1
FP_PDN_HWIDTH: 3.1
FP_PDN_VSPACING: 15.5
FP_PDN_HSPACING: 15.5
FP_PDN_VPITCH: 90
FP_PDN_HPITCH: 90
ERROR_ON_PDN_VIOLATIONS: false

# Magic variables
MAGIC_DRC_USE_GDS: true

