name: Run All
on: 
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        remove-codeql: "true"
        remove-docker-images: "true"
        root-reserve-mb: 20480
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-dependencies
      name: Install Cached Dependencies
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make setup
    - name: Run RTL Verification
      env:
        COCOTB_ARGS: "--CI -verbosity debug -tag CI"
      run: |
        make cocotb-verify-all-rtl
    - name: Check RTL Verification Results
      run: |
        simv="$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/*-compilation/sim.vvp"
        if [ -f $simv ]; then
            echo 'File exists.'
        else
            echo "Error: file $simv not found"
            echo "Error: compilation failed"
            exit -1
        fi
        cat "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/runs.log"
        summary=$(cat "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/runs.log" | tail -n 1)
        echo "# RTL Simulation Result:\n\n$summary" >> $GITHUB_STEP_SUMMARY
        cnt=$(grep -c "failed" "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/runs.log")
        if [[ $cnt -ne 1 ]]; then exit 1; fi
        rm -rf $GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI
    - name: Install nix
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm --extra-conf "
            extra-substituters = https://openlane.cachix.org
            extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
        "
    - name: Run OpenLane
      run: make user_project_wrapper
    - name: Run GL Verification
      env:
        COCOTB_ARGS: "--CI -verbosity debug -tag CI-GL"
      run: |
        make cocotb-verify-all-gl
    - name: Check GL Verification Results
      run: |
        simv="$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI-GL/*-compilation/sim.vvp"
        if [ -f $simv ]; then
            echo 'File exists.'
        else
            echo "Error: file $simv not found"
            echo "Error: compilation failed"
            exit -1
        fi
        cat "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI-GL/runs.log"
        summary=$(cat "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI-GL/runs.log" | tail -n 1)
        echo "# GL Simulation Result:\n\n$summary" >> $GITHUB_STEP_SUMMARY
        cnt=$(grep -c "failed" "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI-GL/runs.log")
        if [[ $cnt -ne 1 ]]; then exit 1; fi
