name: Run All
on: 
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-dependencies
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make setup
    - name: Run RTL Verification
      env:
        COCOTB_ARGS: "--CI -verbosity debug -tag CI"
      run: |
        make cocotb-verify-all-rtl
    - name: Check RTL Verification Results
      run: |
        ls ./verilog/dv/cocotb/sim/*/*/*.log
        ls ./verilog/dv/cocotb/sim/*/*/simv
        ls ./verilog/dv/cocotb/sim/*/*/*
        ls ./verilog/dv/cocotb/sim/*/*-compilation/*
        simv="$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/*-compilation/simv"
        if [ -f $simv ]; then
            echo 'File exists.'
        else
            echo "Error: file $simv not found"
            echo "Error: compilation failed"
            exit -1
        fi
        cat "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/runs.log"
        summary=$(cat "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/runs.log" | tail -n 1)
        echo "# RTL Simulation Result: $summary" >> $GITHUB_STEP_SUMMARY
        cnt=$(grep -c "failed" "$GITHUB_WORKSPACE/verilog/dv/cocotb/sim/CI/runs.log")
        if [[ $cnt -ne 1 ]]; then exit 1; fi
    - name: Debug
      if: always()
      run: |
          cat ./verilog/dv/cocotb/sim/*/*/*.log
      #    - name: Install nix
      #      run: |
      #        curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm --extra-conf "
      #            extra-substituters = https://openlane.cachix.org
      #            extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
      #        "
      #    - name: Run OpenLane
      #      run: make user_project_wrapper
      #    - name: Run RTL Verification
      #      env:
      #        COCOTB_ARGS: "--CI -verbosity debug -tag CI"
      #      run: |
      #        make cocotb-verify-all-gl
