name: Run All
on: 
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make setup
    - name: Run RTL Verification
      run: |
        make cocotb-verify-all-rtl
    - name: Debug
      if: always()
      run: |
          cat ./verilog/dv/cocotb/sim/*/*/*.log

